[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mr_hud"
version = "1.0.0"
description = "Adds a 'HUD' area showing session data above the chat"
authors = [{name = "Assistant"}]
